In [1]:
import numpy as np

#### Array Operations

##### arithmatic operations

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,0])

In [3]:
a1+ a2

array([ 7,  9, 11, 13,  5])

In [4]:
a1 - a2

array([-5, -5, -5, -5,  5])

In [7]:
a1 / a2

C:\Users\Ayush mishra\AppData\Local\Temp\ipykernel_13956\108435935.py:1: RuntimeWarning: divide by zero encountered in divide
  a1 / a2


array([0.16666667, 0.28571429, 0.375     , 0.44444444,        inf])

In [8]:
a1//a2

C:\Users\Ayush mishra\AppData\Local\Temp\ipykernel_13956\3118732420.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  a1//a2


array([0, 0, 0, 0, 0])

In [9]:
a2* 2

array([12, 14, 16, 18,  0])

In [10]:
a1**2

array([ 1,  4,  9, 16, 25])

In [11]:
a1 *a2

array([ 6, 14, 24, 36,  0])

##### Brodcasting

In [12]:
l = [10,20,30,40]
arr = np.array(l)

In [13]:
arr +10

array([20, 30, 40, 50])

In [14]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

##### Deep and shallow copy

In [16]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [18]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
a 
b = a.copy()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:

b[0]

np.int64(1)

In [22]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

##### MAtrix operations

In [23]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])


In [24]:
A

array([[1, 2],
       [3, 4]])

In [25]:
B

array([[5, 6],
       [7, 8]])

In [26]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [28]:
A.T

array([[1, 3],
       [2, 4]])

In [29]:
B.T

array([[5, 7],
       [6, 8]])

###### Advanced Array Manipulation
###### Stacking Array

In [30]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [31]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [34]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [37]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]