In [1]:
import numpy as np

In [4]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])


##### General Questions

In [5]:

import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [20]:
# Get the shape of the matrix.
data.shape
data.dtype

dtype('int64')

In [35]:
# Find the avg age of student.
age = data[:,:1]
print(f"Avg Age is {age.mean()}.")

Avg Age is 18.4.


In [36]:
# Extract Maths marks of all studentd.
Math_marks = data[:,1:2]
print(f"Maths Marks are {Math_marks}.")

Maths Marks are [[85]
 [92]
 [76]
 [65]
 [90]].


In [37]:
# Find the Highest Science Marks
Science_marks = data[:,2:]
print(f"Maximum Marks is {Science_marks.max()}.")

Maximum Marks is 95.


In [39]:
More_then_90 = (Math_marks > 90)
More_then_90

array([[False],
       [ True],
       [False],
       [False],
       [False]])

In [40]:
# Increse Math marks of all Students by 5.
Incresed_math_Marks = (Math_marks + 5)
Incresed_math_Marks

array([[90],
       [97],
       [81],
       [70],
       [95]])

In [41]:
# Find how many students are younger than 19.
More_then_19 = (age > 19)
More_then_19

array([[False],
       [False],
       [False],
       [False],
       [ True]])

In [43]:
print(f"Avg Math marks {Math_marks.mean()}.")
print(f"Avg Science Marks {Science_marks.mean()}.")

Avg Math marks 81.6.
Avg Science Marks 83.2.


In [52]:
S1 = Math_marks >=80
S1
s2 = Science_marks >=80
s2
S1 & s2

array([[False],
       [ True],
       [False],
       [False],
       [ True]])

In [56]:
import numpy as np

replaced_marks = np.where(Science_marks < 75, 0, Science_marks)
replaced_marks

array([[78],
       [88],
       [95],
       [ 0],
       [85]])